---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: elastic
data:
  node.name: elasticsearch
  discovery.type: single-node
  bootstrap.memory_lock: "true"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  network.host: 0.0.0.0
