apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-logger
  namespace: logging
  labels:
    app.kubernetes.io/name: random-logger
    app.kubernetes.io/instance: logging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: random-logger
      app.kubernetes.io/instance: logging
  template:
    metadata:
      labels:
        app.kubernetes.io/name: random-logger
        app.kubernetes.io/instance: logging
    spec:
      containers:
        - name: logger
          image: logging/logger:v1
          resources: {}
