apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}
  namespace: kube-system
  labels:
{{ include "fluentd.labels" . | indent 4 }}
data:
  # Fluent main configuration
  fluent.conf: |-
    # @include "#{ENV['FLUENTD_PROMETHEUS_CONF'] || 'prometheus'}.conf"
    @include kubernetes.conf
    @include conf.d/*.conf
    {{ .Values.fluentd.outputs |nindent 4 }}

# Kubernetes configuration
  kubernetes.conf: |-
    # Ignore logs from fluentd
    <match fluent.**>
      @type null
    </match>

    {{ .Values.fluentd.kubernetes.sources | nindent 4 }}
    # Pipe out any fluentd container logs
    {{ range .Values.fluentd.kubernetes.ignore }}
    <match kubernetes.var.log.containers.**{{ . }}**.log>
      @type null
    </match>
    {{ end }}

    {{ .Values.fluentd.kubernetes.filters | nindent 4 }}

    {{ range .Values.fluentd.kubernetes.removeKeys }}
    
    <filter {{ .match }}>
      @type record_transformer
      enable_ruby
      remove_keys {{ join "," .keys }}
    </filter>
    {{ end }}
