# v1.7.3-debian-elasticsearch7-1.0

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fluentd.fullname" . }}
  namespace: kube-system
  labels:
{{ include "fluentd.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "fluentd.labels" . | nindent 6 }}
  template:
    metadata:
      labels:   
      {{- include "fluentd.labels" . | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/env: {{ include (print $.Template.BasePath "/env.yaml") . | sha256sum }}
    spec:
      serviceAccount: {{ include "fluentd.fullname" . }}
      serviceAccountName: {{ include "fluentd.fullname" . }}
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
          envFrom:
            - configMapRef:
                name: {{ include "fluentd.fullname" . }}-env
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentd-conf
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
            - name: fluentd-conf
              mountPath: /fluentd/etc/kubernetes.conf
              subPath: kubernetes.conf
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentd-conf
          configMap:
            name: {{ include "fluentd.fullname" . }}
