---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentd.fullname" . }}
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "fluentd.fullname" . }}
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "fluentd.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "fluentd.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "fluentd.fullname" . }}
    namespace: kube-system
